version: '3.8'  

services:
  sqlw:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04  
    environment:
      ACCEPT_EULA: "Y"  
      MSSQL_SA_PASSWORD: "yourStrong(!)password"  
      MSSQL_PID: "Evaluation"  
    ports:
      - "1402:1433"  
    hostname: sqlpreview  
    volumes:
      - vol:/var/opt/mssql  

volumes:
  vol:  
